on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: UniTests
    steps:
      - name: Install dependencies
        run: sudo apt-get install jq chrony expect -y
      - name: Install Go
        run: |
          wget https://golang.org/dl/go1.18.2.linux-amd64.tar.gz
          mkdir /home/runner/goinstall
          sudo tar -C /home/runner/goinstall -xzf go1.18.2.linux-amd64.tar.gz
      - uses: actions/checkout@v3
        with:
          repository: obi-wallet/proxy_contract
      - name: Install Juno
        shell: bash
        run: |
          ./scripts/install_juno.sh
      - name: Install CosmWasm go pkg
        shell: bash
        run: |
          ./scripts/install_cosmwasm.sh
      - name: Initialize Keys
        shell: bash
        run: |
          echo $GOPATH
          ./scripts/expect_wrapper.sh
        env:
          BASHTESTER: ${{ secrets.BASHTESTER }}
          BADTESTER: ${{ secrets.BADTESTER }}
          GOROOT: /home/runner/goinstall/go
          GOPATH: /home/runner/go
          GO111MODULE: on
          PATH: $PATH:/home/runner/goinstall/go/bin:/home/runner/go/bin
      - name: Deploy and Test
        shell: bash
        run: |
          ./scripts/deploy_proxy.sh
        env:
          GOROOT: /home/runner/goinstall/go
          GOPATH: /home/runner/go
          GO111MODULE: on
          PATH: $PATH:/home/runner/goinstall/go/bin:/home/runner/go/bin
