on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: UniTests
    steps:
      - name: Install dependencies
        run: sudo apt-get install make build-essential gcc git jq chrony -y expect
      - name: Install Go
        run: |
          wget https://golang.org/dl/go1.18.2.linux-amd64.tar.gz
          mkdir /home/runner/goinstall
          sudo tar -C /home/runner/goinstall -xzf go1.18.2.linux-amd64.tar.gz
      - uses: actions/checkout@v3
        with:
          name: obi-wallet/proxy_contract
      - name: Installing Juno
        run: ./scripts/install_juno.sh
        env:
          GOROOT: /home/runner/goinstall/go
          GOPATH: /home/runner/go
          GO111MODULE: on
          PATH: $PATH:/usr/local/goinstall/go/bin:/home/runner/go/bin
      - name: Deploying and Testing
        run: |
          bash ./scripts/import_keys.sh
          bash ./scripts/deploy_proxy.sh
        env:
          BASHTESTER: ${{ secrets.BASHTESTER }}
          BADTESTER: ${{ secrets.BADTESTER }}
